version: '3.3'

services:
  react:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    container_name: react
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 5173:5173
    env_file:
      - .env
